# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b02867c9722ff4c1da21cb3a4cddd8d247558116097d591a7011e4faa5946f04b35861827d412391d621d2e1919c2fbc2dc0303046b8a953f6667a8fb4538c06
  twitter_consumer_key: <%= ENV["ECHOWINGS_TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["ECHOWINGS_TWITTER_CONSUMER_SECRET"] %>
  twitter_access_token: <%= ENV["ECHOWINGS_TWITTER_ACCESS_TOKEN"] %>
  twitter_access_token_secret: <%= ENV["ECHOWINGS_TWITTER_ACCESS_TOKEN_SECRET"] %>
  sendgrid_username: <%= ENV["ECHOWINGS_SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["ECHOWINGS_SENDGRID_PASSWORD"] %>

test:
  secret_key_base: c6875e02477f6e24657b88d7aa2d9735e50aec3f5ca6c9531836029ce1ca0454793831f82d6a761a9b633516afb52f6a0227928087b88d5496536f614f641145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
